---
title: "Analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(broom)

good <- read.csv("goodwill_hunting/good_q.csv")
zillow_2020 <- read.csv("goodwill_hunting/zillow_2020.csv")

good_ratings <- read.csv("goodwill_hunting/good_sampled.csv")

```


```{r}

zillow_2020 %>%
  summarize(min = min(x2020_01),
            mean = mean(x2020_01),
            q1 = quantile(x2020_01, c(.25)),
            median = median(x2020_01),
            q3 = quantile(x2020_01, c(.75)),
            max = max(x2020_01))



```


```{r ratings plot}

goodwill_ratings <- read.csv("goodwill_hunting/goodwill_ratings.csv")

```


```{r ratings plot}
goodwill_ratings %>%
  drop_na(x2020_01, rating) %>%
  ggplot(aes(y = rating, x = x2020_01, color = region)) +
  xlim(0,1000000) +
  geom_point() +
  geom_smooth(method = "glm", level = 0, aes(group = 1), color = "black") +
  geom_smooth(level = 0, aes(group = 1), color = "black") +
  theme_classic() +
  labs(x = "Average Housing Price in Store Zip Code",
       y = "Yelp Star Rating",
       title = "Relationship Between Neighborhood Housing Price and Yelp Star Rating",
       color = "Region")

```

```{r plot with colors}

good_ratings %>%
  drop_na(x2020_01, rating) %>%
  ggplot(aes(y = rating, x = x2020_01, color = quartile)) +
  xlim(0,1000000) +
  geom_point() +
  geom_smooth(method = "glm") +
  theme_classic()

```


```{r}

ratings_model <- lm(rating ~ zip_price, data = good_ratings)

ratings_model %>%
  tidy(conf.int = TRUE) %>%
  mutate(p.value = round(p.value, 2)) %>%
  select(term, estimate, std.error, conf.low, conf.high, p.value) %>%
  gt() %>%
  fmt_scientific(columns = vars(estimate, std.error, conf.low, conf.high)) %>%
  cols_label(term = "Variable", estimate = "Estimate", std.error = "Standard Error", 
             conf.low = "Lower Bound", conf.high = "Upper Bound", p.value = "p value") 


```



